### ISSUE TITLE
Sushy-tools 1.1.0 moved virtual media interfaces from system manager to system

### ISSUE THREAD

**Issue by miburke** [redhatci/ansible-collection-redhatci-ocp#174]
A recent change to sushy-tools in version 1.1.0 (https://opendev.org/openstack/sushy-tools/commit/a654a033dece53b8e6eb005025e37643d61144a5) moved the virtual media interfaces from system manager to systems.  The roles/vendors/kvm/tasks/iso.yml playbook in this collection will fail when attempting to run the tasks that eject, insert, and verify virtual media as they are coded to use the system manager interface.

**Comment by thekad** [comment]
cc @redhatci/crucible have you guys seen this pop up? I believe we don't pin the sushy tools version in the role, so unless you upgrade or have installed sushy very recently you won't see this

**Comment by nocturnalastro** [comment]
I haven't seen it but I haven't reinstalled for a bit. @arjuhe Did you see this when you redeployed?
